spring:
  application:
    name: dms


  datasource:
    url: jdbc:postgresql://localhost:5432/dms
    username: dms
    password: dms
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

